app_calendar/urls.py
from django.urls import path, include

from .views import *


app_name = 'app_calendar'
urlpatterns = [
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/(?P<event_id>\d+)/', event, name='event_edit'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personnel/', include('app_personnel.urls')),
    path('calendar/', include('app_calendar.urls')),
    path('', include('app_company.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta name="description" content="HRM Software" />

        <title>{% block title %}{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app_personnel/css/stylesheet.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app_calendar/css/styles.css' %}" />
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header">
            <a class="app-header__logo" href="{% url 'home' %}">HRM Software</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    <input class="app-search__input" type="search" placeholder="Search" />
                    <button class="app-search__button"><i class="fa fa-search"></i></button>
                </li>
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-cog fa-lg"></i> Админ панель</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out fa-lg"></i> Выйти</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                {% if human.image %}
                    <img class="app-sidebar__user-avatar" src="{{human.image.url}}" alt="User Image" height="50px" width="50px"/>
                {% endif %}
                <div>
                    <p class="app-sidebar__user-name">{{ user.username }}</p>
                    <p class="app-sidebar__user-designation">{{ group.name }}</p>
                </div>
            </div>
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item active" href="{% url 'personnel' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Сотрудники</span></a>
                </li>
                {% if perms.app_personnel %}
                <li class="treeview">
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Регистрация</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'create_personnel' %}"><i class="icon fa fa-circle-o"></i>Личные данные I</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'create_data' %}"><i class="icon fa fa-circle-o"></i>Личные данные II</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'add_employment' %}"><i class="icon fa fa-circle-o"></i>Трудоустройство</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'register' %}"><i class="icon fa fa-circle-o"></i> Регистрация в HRM</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'create_employee' %}"><i class="icon fa fa-circle-o"></i>Новый сотруднтк</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                <li>
                    <a class="app-menu__item" href="{% url 'app_calendar:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Календар</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'daily_report' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Ежедневный отчет</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'delegation' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Командировки</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'vacation' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Отпуска</span></a>
                </li>
                <li class="treeview">
                    {% if perms.app_company %}
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Настройки</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    {% endif %}
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'user_list' %}"><i class="icon fa fa-circle-o"></i> Ползователи</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'structure' %}"><i class="icon fa fa-circle-o"></i>Подразделения</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'function_group' %}"><i class="icon fa fa-circle-o"></i>Должности</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'permission_list' %}"><i class="icon fa fa-circle-o"></i>Права доступа</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

templates/base/base_bezpiecznik.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta name="description" content="HRM Software" />

        <title>{% block title %}{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}" />
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        {% block extracss %}
        {% endblock extracss %}
    </head>
    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header">
            <a class="app-header__logo" href="{% url 'personnel' %}">HRM Software</a>
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    <input class="app-search__input" type="search" placeholder="Search" />
                    <button class="app-search__button"><i class="fa fa-search"></i></button>
                </li>
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-cog fa-lg"></i> Админ панель</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out fa-lg"></i> Выйти</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                {% if human.image %}
                    <img class="app-sidebar__user-avatar" src="{{human.image.url}}" alt="User Image" height="50px" width="50px"/>
                {% endif %}
                <div>
                    <p class="app-sidebar__user-name">{{ user.username }}</p>
                    <p class="app-sidebar__user-designation">{{ group.name }}</p>
                </div>
            </div>
            <ul class="app-menu">
                <li>
                    <a class="app-menu__item active" href="{% url 'personnel' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Сотрудники</span></a>
                </li>
                {% if perms.app_personnel %}
                <li class="treeview">
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Регистрация</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'create_personnel' %}"><i class="icon fa fa-circle-o"></i>Личные данные I</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'create_data' %}"><i class="icon fa fa-circle-o"></i>Личные данные II</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'add_employment' %}"><i class="icon fa fa-circle-o"></i>Трудоустройство</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'register' %}"><i class="icon fa fa-circle-o"></i> Регистрация в HRM</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'create_employee' %}"><i class="icon fa fa-circle-o"></i>Новый сотруднтк</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                <li>
                    <a class="app-menu__item" href="{% url 'cal:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Календар</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'daily_report' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Ежедневный отчет</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'delegation' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Командировки</span></a>
                </li>
                <li>
                    <a class="app-menu__item" href="{% url 'vacation' %}"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Отпуска</span></a>
                </li>
                <li class="treeview">
                    {% if perms.app_company %}
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Настройки</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    {% endif %}
                    <ul class="treeview-menu">
                        <li>
                            <a class="treeview-item" href="{% url 'user_list' %}"><i class="icon fa fa-circle-o"></i> Ползователи</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'structure' %}"><i class="icon fa fa-circle-o"></i>Подразделения</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'function_group' %}"><i class="icon fa fa-circle-o"></i>Должности</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
    </body>
</html>

templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'app_personnel/js/script.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>