app_calendar/urls.py
from django.urls import path, include

from .views import *


app_name = 'app_calendar'
urlpatterns = [
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/(?P<event_id>\d+)/', event, name='event_edit'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personnel/', include('app_personnel.urls')),
    path('calendar/', include('app_calendar.urls')),
    path('', include('app_company.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_calendar/models.py
import uuid
from django.db.models.expressions import RawSQL
from app_personnel.models import *
from app_company.models import *
from django.contrib.auth.models import User
from django.db import models
from datetime import date


from django.db import models
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('app_calendar:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'






# class VisibleManager(models.Manager):
#     def __int__(self, username, model):
#         self.username = username
#         self.employee = Employee.objects.get_for_model(model)
#         self.model = model
#         self.name = 'visible_for_{}'.format(username)
#
#     def get_queryset(self):
#         return super().get_queryset().filter(id__in=self._get_visible_filter())
#
#     def _get_visible_filter(self):
#         return RawSQL("select object_id from aclapp_acl where username = %s and model_conent_type = %s",
#                       (self.username, self.content_type.id,))
#
#
# def accessible_objects(self, user):
#     return VisibleManager(user.usename, Delegation)





    # @property
    # def is_overdue(self):
    #     if self.employee and date.today() > self.employee:
    #         return True
    #     return False




#
# class DepSubordinate(models.Model):
#     superior = models.ForeignKey(DepartamentE, on_delete=models.CASCADE, verbose_name='начальник')
#     subordinate = models.ManyToManyField(Personnel, verbose_name='сотрудник')
#
#     def __str__(self):
#         return f"{self.superior}, {self.subordinate}"
#
#     class Meta:
#         verbose_name = 'Распределение'
#         verbose_name_plural = 'Распределение'
#         ordering = ['id']
#

app_calendar/forms.py
from django import forms
from app_calendar.models import *

from django.forms import ModelForm, DateInput
from .models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
          'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
          'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

app_calendar/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from app_calendar.models import Delegation
from django.contrib.auth.models import User, Group

import calendar
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe

from .forms import EventForm
from .models import *
from .utils import Calendar


class CalendarView(generic.ListView):
    model = Event
    template_name = 'app_calendar/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('app_calendar:calendar'))
    return render(request, 'app_calendar/event.html', {'form': form})

app_calendar/templates/app_calendar/calendar.html
{% extends 'base/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}

<div class="row">
      <div class="col-md-12">
          <div class="tile">
              <div class="tile-body">
                  <div class="table-responsive">
                      <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                          <div class="row">
                              <div class="col-sm-12">
                                  <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                      <thead>
									  	<div class="clearfix">
                                            <span class="left m-2" style="font-size: 20px;">{{ request.user }}</span>
											<a class="btn btn-info right" href="{% url 'app_calendar:calendar' %}?{{ prev_month }}"> Previous Month </a>
											<a class="btn btn-info right" href="{% url 'app_calendar:calendar' %}?{{ next_month }}"> Next Month </a>
											<a class="btn btn-info left" href="{% url 'app_calendar:event_new' %}"> New Event </a>
										</div>
                                        <div style="color: blueviolet;">
                                            {{ calendar }}
                                        </div>
                                      </thead>
                                  </table>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

app_calendar/templates/app_calendar/event.html
{% extends 'base/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="row">
      <div class="col-md-12">
          <div class="tile">
              <div class="tile-body">
                  <div class="table-responsive">
                      <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                          <div class="row">
                              <div class="col-sm-12">
                                  <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                      <thead>

                                        <div class="clearfix">
                                          <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
                                        </div>
                                        {% if form.errors %}
                                            {% for field in form %}
                                                {% for error in field.errors %}
                                                    <div class="alert alert-danger">
                                                        {{ field.label }} <strong>{{ error|escape }}</strong>
                                                    </div>
                                                {% endfor %}
                                            {% endfor %}
                                            {% for error in form.non_field_errors %}
                                                <div class="alert alert-danger">
                                                    {{ field.label }} <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endif %}

                                        <form method="post">
                                          {% csrf_token %}
                                          <table class="form form-table">
                                            {{ form }}
                                            <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
                                          </table>
                                        </form>
                                    </thead>
                                  </table>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}