app_personnel/urls.py
from django.contrib import admin
from django.urls import path, include

from app_personnel.views import *


urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('personnel/', ListPersonnelView.as_view(), name='personnel'),
    path('create_personnel/', CreatePersonnel.as_view(), name='create_personnel'),
    path('personnel/<slug:slug>/', PersonnelIdDetail.as_view(), name='human'),

    path('create_data/', CreatePersonnelData.as_view(), name='create_data'),
    path('personnel_data_detail/<int:pk>/', PersonnelDataDetail.as_view(), name='personnel_data_detail'),


    path('employee_list/', ListEmployeeView.as_view(), name='employee_list'),
    path('employee_detail/<int:pk>/', EmployeeDetail.as_view(), name='employee_detail'),
    path('create_employee/', CreateEmployee.as_view(), name='create_employee'),


    path('add_employment/', EmploymentCreate.as_view(), name='add_employment'),

    path('delegation/', your_delegation, name='delegation'),
    path('create_delegation/', CreateDelegation.as_view(), name='create_delegation'),
    path('update_delegation/<int:pk>/', UpdateDelegation.as_view(), name='update_delegation'),
    path('delete_delegation/<int:pk>/', DeleteDelegation.as_view(), name='delete_delegation'),
    path('vacation/', your_vacation, name='vacation'),
    path('create_vacation/', CreateVacation.as_view(), name='create_vacation'),
    path('update_vacation/<int:pk>/', UpdateVacation.as_view(), name='update_vacation'),
    path('delete_vacation/<int:pk>/', DeleteVacation.as_view(), name='delete_vacation'),
    path('daily_report/', your_daily_report, name='daily_report'),
    path('create_daily_report/', CreateDailyReport.as_view(), name='create_daily_report'),
    path('update_daily_report/<int:pk>/', UpdateDailyReport.as_view(), name='update_daily_report'),
    path('delete_daily_report/<int:pk>/', DeleteDailyReport.as_view(), name='delete_daily_report'),
    path('detail_report/<int:pk>/', DetailDailyReport.as_view(), name='detail_report'),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# urlpatterns += [
#     path(r'^delegation/$', DelegationUserListView.as_view(), name='my-user'),
# ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personnel/', include('app_personnel.urls')),
    path('calendar/', include('app_calendar.urls')),
    path('', include('app_company.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_personnel/models.py
import uuid
from datetime import datetime

from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from app_company.models import *
from django.db import models
from django.contrib.auth.models import User, Group, Permission


class Employee(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    employee = models.OneToOneField('Personnel', on_delete=models.CASCADE, null=True, verbose_name='сотрудник')
    function = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, verbose_name='Должность')
    departament = models.ForeignKey(Departament, on_delete=models.SET_NULL, null=True,
                                    verbose_name='Подразделение фирмы')

    def get_absolute_url(self):
        return reverse('employee-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.employee}, {self.function}, {self.departament}"

    class Meta:
        ordering = ['employee']


class Personnel(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = [
        (MALE, 'Мужчина'),
        (FEMALE, 'Женшина')
    ]

    """uuid nie wspólpracuje z html przy wprowadzeniu danych powinno nastąpić automatyczne pobranie danych tj. Unique ID; do sprawdzenia później"""
    # id_uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    last_name = models.CharField(max_length=40, verbose_name='Фамилия')
    first_name = models.CharField(max_length=40, verbose_name='Имя')
    fathers_name = models.CharField(max_length=40, null=True, blank=True, verbose_name='Отчество')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    image = models.ImageField(upload_to='photos/%Y/%m/%d', null=True, blank=True, verbose_name='фото сотрудника')
    gender = models.CharField(max_length=1, choices=GENDERS, null=True, blank=True, verbose_name='Пол')
    email = models.EmailField(max_length=40, null=True, blank=True, verbose_name='e-mail')
    phone = models.CharField(max_length=30, null=True, blank=True, verbose_name='телефон')
    is_acceptance = models.BooleanField(default=True, verbose_name='Zatwierdzić')

    def get_absolute_url(self):
        return reverse('personnel', kwargs={'slug': self.slug})


    def __str__(self):
        if self.fathers_name is None:
            return f"{self.last_name}, {self.first_name}"
        return f"{self.last_name}, {self.first_name}, {self.fathers_name}"


    class Meta:
        verbose_name = 'сотрудника'
        verbose_name_plural = 'сотрудники'
        ordering = ['last_name']


class Employment(models.Model):
    CONTRACT_OF_EMPLOYMENT_A_FIXTED_TERM = 'CF'
    CONTRACT_OF_EMPLOYMENT_IDENFITE_PERIOD = 'CI'
    CONTRACT_AGREEMENT = 'CA'
    MANAGEMENT_CONTRACT = 'MC'
    CONTRACTS = [
        (CONTRACT_OF_EMPLOYMENT_A_FIXTED_TERM, 'Трудовой договор на неопределенный срок'),
        (CONTRACT_OF_EMPLOYMENT_IDENFITE_PERIOD, 'Срочный трудовой договор'),
        (CONTRACT_AGREEMENT, 'Договор подряда'),
        (MANAGEMENT_CONTRACT, 'Договор на оказание услуги')
    ]

    employee = models.OneToOneField(Personnel, on_delete=models.CASCADE, primary_key=True, verbose_name='сотрудник')
    contract = models.CharField(max_length=2, choices=CONTRACTS, verbose_name='тип договора')
    employment_date_beginning = models.DateField(verbose_name='дата начала работы')
    employment_date_ending = models.DateField(blank=True, null=True, verbose_name='дата окончания контракта')
    # contract_for_an_indefinite_period = models.BooleanField(employment_date_ending)
    salary = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Размер зар. п.')
    uploadedFile = models.FileField(upload_to='files/%Y/%m/%d', verbose_name='скану документов', null=True, blank=True)
    uploadedFile_date = models.DateField(verbose_name='дата годности документа', null=True, blank=True)
    education_remarks = models.TextField(blank=True, null=True, verbose_name='замечания по образованию')
    deadline = models.DateField(blank=True, null=True, verbose_name=' срок устрониения')

    def get_absolute_url(self):
        return reverse('employment-detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.employee}"

    class Meta:
        verbose_name = 'Трудоустройство'
        verbose_name_plural = 'Трудоустройство'
        ordering = ['employee']


class PersonnelData(models.Model):
    employee = models.OneToOneField(Personnel, on_delete=models.CASCADE, primary_key=True, verbose_name='сотрудник')
    born = models.DateField(verbose_name='День рождения')
    birth_place = models.CharField(max_length=50, verbose_name='Место рождения')
    birth_country = models.CharField(max_length=50, verbose_name='Страна рождения')
    '''living'''
    country = models.CharField(max_length=50, verbose_name='Страна постоянного проживания')
    city = models.CharField(max_length=50, verbose_name='Город постоянного проживания')
    post_code = models.CharField(max_length=50, verbose_name='Почтовый индекс')
    street = models.CharField(max_length=100, verbose_name='Улица')
    street_number = models.IntegerField(verbose_name='Номер дома')
    house_number = models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')
    '''education'''
    PRIMARY_EDUCATION = 'PE'
    SECONDARY_EDUCATION = 'SE'
    HIGHER_EDUCATION = 'HE'
    EDUCATION = [
        (PRIMARY_EDUCATION, 'Начальное образование'),
        (SECONDARY_EDUCATION, 'Среднее образование'),
        (HIGHER_EDUCATION, 'Высшее образование')
    ]
    education = models.CharField(max_length=2, choices=EDUCATION, verbose_name='образование')
    # qualifications = models.ManyToManyField(Qualifications, null=True, blank=True, verbose_name='Квалификации')
    uploadedFile = models.FileField(upload_to='files/%Y/%m/%d', verbose_name='скану документов', null=True, blank=True)
    uploadedFile_date = models.DateField(blank=True, null=True, verbose_name='дата годности документа')
    is_acceptance = models.BooleanField(default=True, verbose_name='Zatwierdzić')

    def __str__(self):
        return f"{self.employee}"

    class Meta:
        verbose_name = 'Личные данные'
        verbose_name_plural = 'Личные данные'
        ordering = ['employee']


class Delegation(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    employee = models.ForeignKey(Personnel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='сотрудник')
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    cause = models.TextField(verbose_name='цель командировки')
    date_start = models.DateField(verbose_name='дата выезда')
    date_end = models.DateField(verbose_name='дата возвращения')
    departure_reason = models.CharField(max_length=150, verbose_name='Основание выезда')
    scan_of_documents = models.FileField(upload_to='files/%Y/%m/%d', null=True, blank=True,
                                         verbose_name='Приказ о направлении сотрудника в командировку')

    class Meta:
        verbose_name = 'командировка'
        verbose_name_plural = 'командировка'
        ordering = ['date_start']
        # permissions = [('can_deliver_pizzas', 'Can deliver pizzas')]

    def __str__(self):
        return '%s (%s)' % (self.id, self.employee)


class Vacation(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    employee = models.ForeignKey(Personnel, on_delete=models.SET_NULL, null=True, verbose_name='Сотрудник')
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_start = models.DateField(verbose_name='Дата начала отпуска')
    date_end = models.DateField(verbose_name='Дата окончания отпуска')
    is_acceptance = models.BooleanField(default=True, verbose_name='Согласовано')

    class Meta:
        verbose_name = 'Отпуск'
        verbose_name_plural = 'Отпуск'
        ordering = ['date_start', 'is_acceptance']
        # permissions = [('can_deliver_pizzas', 'Can deliver pizzas')]

    def __str__(self):
        return '%s (%s)' % (self.id, self.employee)


class DailyReport(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID")
    employee = models.ForeignKey(Personnel, on_delete=models.SET_NULL, null=True, verbose_name='Сотрудник')
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_start = models.DateTimeField(verbose_name='Дата и время начала работы', default=datetime.now)
    date_end = models.DateTimeField(verbose_name='Дата и время окончания работы', default=datetime.now)
    report = models.TextField(verbose_name='Ежедневный отчет')

    class Meta:
        verbose_name = 'Ежедневный отчет'
        verbose_name_plural = 'Ежедневный отчет'
        ordering = ['date_start',]
        # permissions = [('can_deliver_pizzas', 'Can deliver pizzas')]

    def __str__(self):
        return '%s (%s)' % (self.id, self.employee)

app_personnel/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from .models import *


class AddPersonnelForm(forms.Form, forms.ModelForm):
    class Meta:
        model = Personnel
        fields = ['last_name', 'first_name',
                  'fathers_name', 'slug', 'image',
                  'gender', 'email', 'phone', 'is_acceptance']


class AddEmployeeForm(forms.Form, forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['user', 'employee', 'function', 'departament']


class DateInput(forms.DateInput):
    input_type = 'date'


class AddPersonnelDataForm(forms.Form, forms.ModelForm, forms.DateInput):
    born = forms.DateField(widget=DateInput)
    uploadedFile_date = forms.DateField(widget=DateInput)
    class Meta:
        model = PersonnelData
        fields = ['employee', 'born', 'birth_place', 'birth_country',
                  'country', 'city', 'post_code', 'street', 'street_number', 'house_number',
                  'education', 'uploadedFile', 'uploadedFile_date', 'is_acceptance']
        widget = ({'born': DateInput()},
                  {'uploadedFile_date': DateInput()})


class AddEmploymentForm(forms.Form, forms.ModelForm, forms.DateInput):
    employment_date_beginning = forms.DateField(widget=DateInput)
    employment_date_ending = forms.DateField(widget=DateInput)
    uploadedFile_date = forms.DateField(widget=DateInput)
    deadline = forms.DateField(widget=DateInput)
    class Meta:
        model = Employment
        fields = ['employee',
                  'contract', 'employment_date_beginning', 'employment_date_ending',
                  'salary', 'uploadedFile', 'uploadedFile_date', 'education_remarks', 'deadline']
        widget = ({'employment_date_beginning': DateInput()},
                  {'employment_date_ending': DateInput()},
                  {'uploadedFile_date': DateInput()},
                  {'deadline': DateInput()})


class AddDelegationForm(forms.ModelForm, forms.DateInput):
    # cause = models.TextField()
    date_start = forms.DateField(widget=DateInput)
    date_end = forms.DateField(widget=DateInput)
    # departure_reason = models.CharField()
    # scan_of_documents = models.FileField()

    class Meta:
        model = Delegation
        # exclude = ['username',]
        # fields = '__all__'
        fields = ['employee', 'username', 'cause', 'date_start', 'date_end', 'departure_reason', 'scan_of_documents']
        widget = {'date_start': DateInput()}, {'date_end': DateInput()}


class AddVacationForm(forms.ModelForm, forms.DateInput):
    date_start = forms.DateField(widget=DateInput)
    date_end = forms.DateField(widget=DateInput)

    class Meta:
        model = Vacation
        fields = ['employee', 'username', 'date_start', 'date_end', 'is_acceptance']
        widget = {'date_start': DateInput()}, {'date_end': DateInput()}


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class AddDailyReportForm(forms.ModelForm, forms.DateTimeInput):
    date_start = forms.DateTimeField(widget=DateTimeInput)
    date_end = forms.DateTimeField(widget=DateTimeInput)

    class Meta:
        model = DailyReport
        fields = ['employee', 'username', 'date_start', 'date_end', 'report']
        widget = {'date_start': DateTimeInput()}, {'date_end': DateTimeInput()}

app_personnel/templates/app_personnel/add_personnel.html
{% extends 'app_personnel/index.html' %}

{% block title %}
    <title>{{title}}</title>
{% endblock %}

{% block content %}
<style>
    form {
        margin-left: 15%;
    }
</style>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    <script>document.write('<a href="' + document.referrer + '">Go Back</a>');</script>
</form>

{% endblock %}

app_personnel/templates/app_personnel/add_personnel_data.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event List{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Add Personnel</h1>
        <p>Event List</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Event List</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" role="grid" aria-describedby="sampleTable_info">
                                <h2><strong>Регистрация: </strong>личных данных нового сотрудника</h2>
                                    <tbody>
                                        <form action="{% url 'create_data' %}" method="post" enctype="multipart/form-data" class="form-horizontal form-bordered">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    {% if not PersonnelData.employee %}
                                                            <p><label class="form-label" for="{{ form.employee.id_for_label }}">{{ form.employee.label }}</label>{{ form.employee }}</p>
                                                    {% endif %}
                                                </div>
                                                    </th>
                                                <tr role="row" class="odd" >
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.born.id_for_label }}"></label>
                                                            <input type="date" id="{{ form.born.id_for_label }}" name="born" class="form-control" placeholder="День рождения">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.birth_place.id_for_label }}"></label>
                                                            <input type="text" id="{{ form.birth_place.id_for_label }}" name="birth_place" class="form-control" placeholder="Место рождения">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.birth_country.id_for_label }}"></label>
                                                            <input type="text" id="{{ form.birth_country.id_for_label }}" name="birth_country" class="form-control" placeholder="Страна рождения">
                                                        </div>
                                                    </th>
                                                </tr>
                                                <tr role="row" class="odd" >
                                                    <th><div class="col-md-12">
                                                    <label class="form-label" for="{{ form.country.id_for_label }}"></label>
                                                            <input type="text" id="{{ form.country.id_for_label }}" name="country" class="form-control" placeholder="Страна постоянного проживания">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.city.id_for_label }}"></label>
                                                            <input type="text" id="{{ form.city.id_for_label }}" name="city" class="form-control" placeholder="Город постоянного проживания">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.post_code.id_for_label }}"></label>
                                                            <input type="number" id="{{ form.post_code.id_for_label }}" name="post_code" class="form-control" placeholder="Почтовый индекс"></p>
                                                        </div>
                                                    </th>
                                                </tr>
                                                <tr role="row" class="odd" >
                                                    <th><div class="col-md-12">
                                                    <label class="form-label" for="{{ form.street.id_for_label }}"></label>
                                                            <input type="text" id="{{ form.street.id_for_label }}" name="street" class="form-control" placeholder="Улица">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.street_number.id_for_label }}"></label>
                                                            <input type="number" id="{{ form.street_number.id_for_label }}" name="street_number" class="form-control" placeholder="Номер дома">
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.house_number.id_for_label }}"></label>
                                                            <input type="number" id="{{ form.house_number.id_for_label }}" name="house_number" class="form-control" placeholder="Номер квартиры"></p>
                                                        </div>
                                                    </th>
                                                </tr>
                                                <tr role="row" class="odd" >
                                                    <th><div class="col-md-12">
                                                            <p><label class="form-label" for="{{ form.education.id_for_label }}">{{ form.education.label }}</label>{{ form.education }}</p>
                                                        </div>
                                                    </th>
                                                    <th><div class="col-md-12">
                                                        <p><label class="form-label" for="{{ form.uploadedFile.id_for_label }}">{{ form.uploadedFile.label }}</label>{{ form.uploadedFile }}</p>
                                                        </div>
                                                    </th>

                                                    <th><div class="col-md-12">
                                                        <label class="form-label" for="{{ form.uploadedFile_date.id_for_label }}"></label>
                                                            <input type="date" id="{{ form.uploadedFile_date.id_for_label }}" name="uploadedFile_date" class="form-control" placeholder="'дата годности документа">
                                                        </div>
                                                    </th>

                                                </tr>
                                                    <th>
                                                        <div class="col-md-12">
                                                        <p><label class="form-label" for="{{ form.is_acceptance.id_for_label }}">{{ form.is_acceptance.label }}</label>{{ form.is_acceptance }}</p>
                                                        </div>
                                                    </th>
                                                    <th>
                                                        <div class="col-sm-12 ">
                                                            <input type="submit" class="page-link" value="Save" />
                                                        </div>
                                                    </th>
                                                </tr>
                                            </div>
                                        </form>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}

app_personnel/templates/app_personnel/create.html
{% extends 'app_personnel/index.html' %}

{% block title %}
    <title>{{title}}</title>
{% endblock %}

{% block content %}
<style>
    form {
        margin-left: 15%;
    }
</style>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    <script>document.write('<a href="' + document.referrer + '">Go Back</a>');</script>
</form>
{% endblock %}

app_personnel/templates/app_personnel/employee.html
{% extends 'app_personnel/index.html' %}

{% block title %}
    <title>{{title}}</title>
{% endblock %}

{% block content %}
<style>
    form {
        margin-left: 15%;
    }
</style>

<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    <script>document.write('<a href="' + document.referrer + '">Go Back</a>');</script>
</form>
{% endblock %}

app_personnel/templates/app_personnel/nowy_test.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event List{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Сотрудники организации</h1>
        <p>Event List</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Event List</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover table-bordered dataTable no-footer"  role="grid" aria-describedby="sampleTable_info">
                                <thead>
                                <h2><strong>{{employee_detail.employee}} </strong>
                                    {{human.first_name}}</p>
                                </h2>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">
                                            {% if human.image %}
                                                <p><img class="img-article-left thumb" height="100px" width="150px" src="{{human.image.url}}"></p>
                                            {% endif %}
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">
                                            <div class="contest">
                                                {% autoescape on %}
                                                <p class="app-sidebar__user-name">ФИО: &nbsp; {{employee_detail.employee}} &nbsp; {{human.first_name}}
                                                    {% if human.fathers_name %}
                                                        &nbsp; {{human.fathers_name}}
                                                    {% endif %}</p><p></p>
                                                {% endautoescape %}
                                                <p class="app-sidebar__user-name">Должность: &nbsp; {{employee_detail.function}}</p>
                                                <p class="app-sidebar__user-name">подразделение фирмы: &nbsp;{{employee_detail.departament}}</p>
                                                    <div class="contest_scorecard">
                                                        <h1>Scorecard</h1>
                                                        {% for i in employee.personnel_set.all %}
                                                            <li>{{ i.email }}</li>
                                                            <li>{{ i.departament }}</li>
                                                            <li>{{ i.phone }}</li>
                                                        {% endfor %}
                                                    </div>
                                                <a class="btn btn-xs btn-secondary btn-sm" href="#" data-toggle="tooltip" title="delete" role="button" ><i class="fa fa-angle-right"> Дать права </i></a>
                                                <script>document.write('<a href="' + document.referrer + '">Go Back</a>');</script>
                                            </div>
                                        </th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>





{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}